USE senainoteshenry

CREATE TABLE Usuarios(
UsuarioId INT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Senha VARCHAR(MAX) NOT NULL,
Telefone VARCHAR(15)NOT NULL,
DataCadastro DATETIME NOT NULL,
DataAtualizacao DATETIME NOT NULL,
TipoUsuarioId INT,
FOREIGN KEY (TipoUsuarioId) REFERENCES TipoUsuario(TipoUsuarioId)
);



CREATE TABLE TipoUsuario(
TipoUsuarioId INT PRIMARY KEY IDENTITY(1,1),
Descricao VARCHAR(50) NOT NULL
);

ALTER TABLE TipoUsuario
ALTER COLUMN descricao VARCHAR(50);

CREATE TABLE Notas(
NotasID INT PRIMARY KEY IDENTITY(1,1),
Titulo VARCHAR(100) NOT NULL,
ConteudoNotas TEXT NOT NULL,
UsuarioId INT,
FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId),
Lixeira BIT,
Imagem VARCHAR(MAX),
Arquivado BIT
);

ALTER TABLE Notas ALTER COLUMN ConteudoNotas VARCHAR(250);

CREATE TABLE TagNotas(
TagNotasId INT PRIMARY KEY IDENTITY(1,1),
NotasId INT,
FOREIGN KEY (NotasId) REFERENCES Notas(NotasId),
TagsId INT,
FOREIGN KEY (TagsId) REFERENCES Tags(TagsId)
);

CREATE TABLE Tags(
TagsId INT PRIMARY KEY IDENTITY(1,1),
NomeTag VARCHAR(100) NOT NULL 
);
