CREATE DATABASE SenaiNotes

CREATE TABLE Usuarios(
UsuarioId INT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
Telefone VARCHAR(15) NOT NULL,
DataCadastro DATE NOT NULL,
DataAtualizacao DATE NOT NULL,
TipoUsuarioId INT,
FOREIGN KEY (TipoUsuarioId) REFERENCES TipoUsuario(TipoUsuarioId)
);

CREATE TABLE TipoUsuario(
TipoUsuarioId INT PRIMARY KEY IDENTITY(1,1),
Descricao VARCHAR NOT NULL
);

CREATE TABLE Notas(
NotasID INT PRIMARY KEY IDENTITY(1,1),
Titulo VARCHAR(100) NOT NULL,
Subtitulo VARCHAR(100) NOT NULL,
ConteudoNotas TEXT NOT NULL,
UsuarioId INT,
FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);

CREATE TABLE Lixeira(
LixeiraId INT PRIMARY KEY IDENTITY(1,1),
NotasId INT,
FOREIGN KEY (NotasId) REFERENCES Notas(NotasId)
);

CREATE TABLE TagNotas(
TagNotasId INT PRIMARY KEY IDENTITY(1,1),
NotasId INT,
FOREIGN KEY (NotasId) REFERENCES Notas(NotasId),
TagsId INT,
FOREIGN KEY (TagsId) REFERENCES Tags(TagsId)
);

CREATE TABLE Tags(
TagsId INT PRIMARY KEY IDENTITY(1,1),
NomeTag VARCHAR(100) NOT NULL 
);